### ISSUE TITLE
Deleted files?

### ISSUE THREAD

**Issue by ninjasort** [arve0/metalsmith-changed#10]
Does this handle files deleted?

For example, if I delete a file but haven't modified it. Will it also delete the existing file in the destination folder?

**Comment by arve0** [comment]
Currently, no, it will not delete any files.

**Comment by ninjasort** [comment]
Okay, is that possible to have happen? I think it should mirror the src directory in cases where files are deleted. Wouldn't that makes sense? If I delete a file in the `src/assets/img/foo.png` for example, it should also delete within the destination directory `dist/assets/img/foo.png`.

I was recently discussing these issues [here](https://github.com/mrajo/metalsmith-differential/issues/3)

Here's an idea:

> The files aren't external. They sit in src/data. And regardless, you can still see the whole project from the process.cwd()
> 
> I think what I'm getting at is that there needs to be somewhat of a dependency graph built to map the data across files.
> 
> Along with this, would need to be a cache json file that keeps track of all changes. When a file is changed it could do this:
> 
> [check the current directory and format it in json for all current files] =>
> 
> [analyze the layout files and data files to build a dependency graph in json] =>
> 
> [diff both the current directory json and dependency graph json with the current cache json and graph json to see if any current files are deleted, modified, or created] =>
> 
> [perform necessary clean ups on the files in the destination folder] =>
> 
> [create a new version of the cache based on changes in json] =>
> 
> [pass the new metadata on to the build] =>

**Comment by arve0** [comment]
With [previous version `v0.2.0`](https://github.com/arve0/metalsmith-changed/tree/cc99b6c1be99c9ce2047125c60195be31f8e84c9) of `metalsmith-changed`, you could absolutely get this to work. I used the idea of mapping source files to output files.

I found this approach messy, and will not pursue it any longer. You are welcome to fork and work of `v0.2.0` if you like.

**Comment by ninjasort** [comment]
Why did you find it messy? The benefits of doing this would dramatically speed up performance and build time. I think it would be well worth the effort - could save hours of build time.

**Comment by arve0** [comment]
Here are a couple of reasons:
- You have no control over plugins that add files after `changed`, and adding `changed` as the last plugin does not make any sense.
  - Possible solution: Add `changed` in the middle of the flow, and at the end, communicate between (more code => messy).
- Mapping single input files to single output files will not always hold. For example `some_article.md` might cause several other files to build (`some_article.html`, `2015-august.html`, ...). Making this relation is hard.
  - Your heuristics might work, but I feel it's hard to think about and hard to confirm it works.

Bottomline, I do not need it (and it will not save me hours, my clean-build is taking 5 seconds). If creating this feature saves you hours, go for it.

**Comment by ninjasort** [comment]
Well, I would expect this plugin to be used directly before each build as it's focused on performance. `.use(changed(config)).build(cb)`

Why wouldn't you just keep an internal `cache.json` instead of mapping every file. If this plugin runs before each build than you have the cache of everything in the `fs.stat` current directory + the metalsmith metadata config `metalsmith.metadata()` and the files from the plugin `.use(function ( files <------- , metalsmith, done) { })`.

Considering that that's a good model of information, wouldn't that be enough to diff everything and run create, delete, put operations?

**Comment by arve0** [comment]
As far as I know, files in src is not available when adding plugin, and deleting files in last step will not save you any time - the files have then already been built.

**Comment by ninjasort** [comment]
You can get the diff the files from `fs.stat` and a cache file. It's not a hard problem to solve.

**Comment by arve0** [comment]
Then do it :smile:

**Comment by arve0** [comment]
This issue is outside this plugin's scope, because creating a dependency graph is not straight forward with the current Metalsmith architecture (I believe).
