### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by sunnysingh** [arve0/metalsmith-changed#2]
I get the following error:

```
Error: Failed to write the file at: /assets/js/site.js
EACCES: permission denied, mkdir '/assets'
    at Error (native)
```

The plugin itself works but only if I keep the clean option enabled (`clean(true)`) which obviously defeats the purpose. I've tried `npm cache clean` and resetting npm permissions. Any help would be greatly appreciated.

**Comment by arve0** [comment]
Do you have that file open?

https://en.m.wikipedia.org/wiki/Lsof

**Comment by sunnysingh** [comment]
@arve0 Doesn't appear so. I've run `lsof | grep assets` in different variations. Are there any other potential causes for this?

**Comment by arve0** [comment]
Seems to be an incompatibility with another plugin or Metalsmith itself:

```
EACCES: permission denied, mkdir '/assets'
```

Why is it trying to create the directory if it's only going to update

```
Error: Failed to write the file at: /assets/js/site.js
```

What version of Metalsmith are you using? I'm using this plugin with version `^1.7.0`.

**Comment by sunnysingh** [comment]
@arve0 I have `^2.1.0` which is latest. I am declaring the plugin at the top right after `clean(false)`. I'll try commenting out each plugin to see who is the culprit when I get a chance.

**Comment by sunnysingh** [comment]
@arve0 Looks like the culprit is the https://github.com/christophercliff/metalsmith-webpack plugin. I'll open an issue on there assuming this has nothing to do with the changed plugin.

**Comment by arve0** [comment]
:+1:
