### ISSUE TITLE
Add smarter pattern matching

### ISSUE THREAD

**Issue by jmatsushita** [arve0/metalsmith-changed#3]
In the same way that extname allows to track files accross extension changes, using a pattern such as:

```
patterns: {
  "index.md":"snippets/*.md"
}
```

would allow to map dependencies to allow rebuilding of content that depends on a number of files. In the example above if (relatively to `index.md`) `snippets/blah.md` was changed, then `index.md` would be rebuilt.

**Comment by arve0** [comment]
~~Would this pattern work?~~

``` js
Metalsmith()
.use(changed.stat)  // register file.stat
.use(plugin1)
.use(plugin2)
.use(changed)  // remove files not to run the expensive (cpu, disk, network, etc) plugin
.use(expensivePlugin)
```

~~Assuming plugins does not alter `file.stat`.~~

**Comment by arve0** [comment]
Special logic like this will not be implemented. Any file that have changed since last build will be passed on to the next plugin. 

You can solve your particular problem something like this:

``` js
.use(function (files) {
  var file1 = files['index.md'];
  var file2 = file['someFile.json'];
  var newestStats = file1.stats.ctime > file2.stats.ctime ? file1.stats : file2.stats;
  var newFile = {
    title: file1.title,
    someProp: file2.someProp
    stats: newestStats
  };
  files['newfile.md'] = newFile;
})
.use(changed())  // newfile.md will be recorded to metalsmith-changed-ctimes.json
```
