### ISSUE TITLE
forcePattern accept array of globs?

### ISSUE THREAD

**Issue by kenhoff** [arve0/metalsmith-changed#8]
Hey there - just wanted to say hi and ask if `forcePattern` can accept an array of globs.

Seems like the documentation says that it can, but when I try I get a `TypeError: micromatch.matcher(): pattern should be a string, regex, or function.` Just wanted to check if that was expected or if it's a bug. 

Thanks!

**Comment by arve0** [comment]
You are correct, I'm using the wrong API on micromatch.

**Comment by arve0** [comment]
Thanks for letting me know. Fixed in `v3.0.0`.

**Comment by kenhoff** [comment]
happy to help! thanks a bunch!
