### ISSUE TITLE
Data files?

### ISSUE THREAD

**Issue by ninjasort** [arve0/metalsmith-changed#9]
When using data files, how does this plugin work?

For example, if I change a global site config: site.yaml, from title: Blog to title: New Blog, how would it know that I have multiple templates that use that {{ site.title }} key? If that has changed in multiple places, it should render those multiple files, right?

**Comment by arve0** [comment]
It would not magically update those files that are dependent on `site.yaml`, `metalsmith-changed` have no way to find which files are dependent on which. If you are aware of how that would work, please let me know.

What you would do, is to make a `force-build`, with the option `force: true`:

``` js
Metalsmith(__dirname)
  .use(changed({ force: true })
```

**Comment by arve0** [comment]
Btw, something like this could work:

``` js
Metalsmith(__dirname)
  .use(changed({ buildAllWhenChanged: patternOfSomeMetaFile })
```

PRs are welcome :octocat:

**Comment by ninjasort** [comment]
Again, the dependency graph would work fine. If data is going into Metalsmith, than that data can be associated with files. In this case, it might require going through all files as a string and regexing for the values. For example, `{{ site.title }}` in `templates/includes/header.liquid`, would need to be mapped. 

```
{
  "site.title": [
    "templates/includes/header.liquid",
    // may also include
    "templates/includes/footer.liquid"
   ]
}
```

Now any time that data changes, it would go through that list:
- check for ignores
- create a new object of files to pass to metalsmith
- build the new files and overwrite what's in the destination directory

**Comment by arve0** [comment]
You can now do a full build by including a pattern to metadata files:

``` js
.use(changed({
  forceAllPattern: ['*.json', 'metadata.txt']
})
```
